paths:
    jquery: "libs/jquery/jquery-min"
    rails: "libs/jquery/rails"
    underscore: "libs/underscore/underscore-min"
    backbone: "libs/backbone/backbone-optamd3-min"
    modelbinding: "libs/backbone/backbone.modelbinding"
    twDropdown: "libs/twitter/bootstrap-dropdown"
    twTransition: "libs/twitter/bootstrap-transition"
    twAlert: "libs/twitter/bootstrap-alert"
    twModal: "libs/twitter/bootstrap-modal"
    twScroll: "libs/twitter/bootstrap-scrollspy"
    twTab: "libs/twitter/bootstrap-tab"
    twTooltip1: "libs/twitter/bootstrap-tooltip"
    twPopover: "libs/twitter/bootstrap-popover"
    twButton: "libs/twitter/bootstrap-button"
    twCollapse: "libs/twitter/bootstrap-collapse"
    twCarousel: "libs/twitter/bootstrap-carousel"
    twTypeahead: "libs/twitter/bootstrap-typeahead"
    handlebars: "libs/handlebars/handlebars.1.0.0.beta.3"
    text: "libs/require/text"
    application: "application"

modules:
  - name: "jquery"
  - name: "rails"
  - name: "underscore"
  - name: "backbone"
  - name: "modelbinding"
  - name: "twDropdown"
  - name: "twTransition"
  - name: "twAlert"
  - name: "twModal"
  - name: "twScroll"
  - name: "twTab"
  - name: "twTooltip1"
  - name: "twPopover"
  - name: "twButton"
  - name: "twCollapse"
  - name: "twCarousel"
  - name: "twTypeahead"
  - name: "handlebars"
  - name: "text"
  - name: "application"

